### ISSUE TITLE
Change size of actual button?

### ISSUE THREAD

**Issue by kenstone** [Savjee/button-text-card#29]
Is there a way to change the size of the actual button? Not just the size of the icon inside the button.  I'm looking at the https://github.com/custom-cards/button-card which has a style property that allows for changing the dimensions of the actual button.

**Comment by Savjee** [comment]
Right now, that's not possible. Good suggestion!
Can you take this up? Otherwise, I'll plan it when I have some spare time.

**Comment by kenstone** [comment]
Sounds good. I'll give it a go.

**Comment by luixal** [comment]
Hi,

just looking for this, is it possible to change card size?

I've tried using card_mod but doesn't seem to work as the card just gets cut off.

Thanks!

**Comment by Savjee** [comment]
Not at this moment, sorry.

**Comment by luixal** [comment]
Ok, just in case someone gets here and really needs it, this is how I managed to change its size.

Let's take this one as an example:

```yaml
type: custom:button-text-card
title: Example
subtitle: Larger example text
icon: mdi:home
large: true
font_color: white
background_color: blue
```

I tweaked it using card_mod, like this:

```yaml
type: custom:button-text-card
title: Example
subtitle: Larger example text
icon: mdi:home
large: true
font_color: white
background_color: blue
style: |
  .flex-container {
    padding: 12px 0px 12px;
    height: 45px;
  }

  .icon-container, .text-container {
    height: 100% !important;
  }
```

Hope it helps someone :)
