### ISSUE TITLE
`tap_action` not working.

### ISSUE THREAD

**Issue by slimcdk** [Savjee/button-text-card#37]
Hi! 

I've have used this card since the beginning of the year, however it stopped worked a few weeks ago. Not sure when, but I can not get any `tap_action` to work.  My tap actions works fine with the regular button card.

I'm currently on Home Assistant 2021.7.1, but it hasn't worked for the past versions.

```yaml
type: custom:button-text-card
title: ...
icon: ...
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    title: ...
    card: !include popup.yaml
 ```

**Comment by bkr1969** [comment]
Ditto. HA does not like tap_action for this card

**Comment by brianewman** [comment]
Still broken on 2022.2.2.  Ok, not really broken since it's not documented, but it would be nice to have.  :-)

**Comment by Savjee** [comment]
@brianewman Are you trying this with browser_mod as well?

For me, this `tap_action` works fine:

```yaml
tap_action:
  action: navigate
  navigation_path: /lovelace/climate
```
