### ISSUE TITLE
Add alignment 

### ISSUE THREAD

**Issue by Gregg-Deaton** [Savjee/button-text-card#46]
please try to add text alignment left, center, right

**Comment by luixal** [comment]
I do this using card_mod, like this:

```yaml
type: custom:button-text-card
title: MyCard
subtitle: My custom message here
icon: mdi:teddy-bear
style: |
  ha-card {
    text-align: right
  }
```

Just in case this helps you :)
