### ISSUE TITLE
This card does not work anymore in HA 2023.4 beta version

### ISSUE THREAD

**Issue by anybody84** [Savjee/button-text-card#47]
Using a config example there is nothing shown in the preview.

![image](https://user-images.githubusercontent.com/37036776/230083836-3e68fe56-6f29-4346-9dc9-e1f50437f034.png)

Also, nothing after saving changes

![image](https://user-images.githubusercontent.com/37036776/230084135-54c0a80e-214b-45dd-9c51-97ddc0087538.png)

And nothing after exiting `Edit mode`

The configuration I used:
```yaml
type: custom:button-text-card
title: Title
subtitle: Subtitle
icon: mdi:lightbulb-outline
```
